doctor-patient-frontend/package-lock.json
doctor-patient-frontend/src/pages/login.js
doctor-patient-frontend/src/pages/registration.js

I'm just putting what I have into main

HelloWorld into main

---

doctor-patient-frontend/package-lock.json
doctor-patient-frontend/package.json
doctor-patient-frontend/src/index.css
doctor-patient-frontend/src/pages/login.js
doctor-patient-frontend/src/pages/registration.js
doctor-patient-frontend/tailwind.config.js

I've added some of the backend for log in and tailwind css for the front end as a whole

More updates for Log in and Registration

---

doctor-patient-frontend/.gitignore
doctor-patient-frontend/package-lock.json
doctor-patient-frontend/package.json
doctor-patient-frontend/src/App.js
doctor-patient-frontend/src/pages/doctorDashboard/doctorDashboard.css
doctor-patient-frontend/src/pages/doctorDashboard/doctorDashboard.js
doctor-patient-frontend/src/pages/patientDashboard/BookAppointmentModal.css
doctor-patient-frontend/src/pages/patientDashboard/BookAppointmentModal.js
doctor-patient-frontend/src/pages/patientDashboard/patientDashboard.css
doctor-patient-frontend/src/pages/patientDashboard/patientDashboard.js

Sets up the Patient and Doctor Dashboard
will elaborate on features lol at some point, but Michael will be taking over on this when hes good to go
I am not planning on merging this(as of right now). This is just the test frontend I have been creating to figure out what backend endpoints are missing

feat: add basic patient and doctor dashboards

---

doctor-patient-frontend/src/pages/patientDashboard/CalorieChart.js
doctor-patient-frontend/src/pages/patientDashboard/patientDashboard.js

feat: add calorie chart

---

src/pages/login.js
src/pages/registration.js

Added the email and password to the registration page along with replacing username with email on the login page

Registration and Login fields changed to add email and password

---

src/pages/login.js
src/pages/patientDashboard/patientDashboard.js
src/pages/registration.js

Just testing out some things to try to get from Registration of New Patient -> Login -> Patient Dashboard
Current Progress

fix: update registration with email and password fields

---

src/pages/patientDashboard/patientDashboard.css
src/pages/patientDashboard/patientDashboard.js

Patients can now fill out a survey for their daily calorie, weight and height check.
This survey can be taken at any time and is not gated to be daily yet
e2e with backend support

feat: allow input of patient metrics

---

src/pages/patientDashboard/patientDashboard.css
src/pages/patientDashboard/patientDashboard.js

Pay Now Button that links to no where. Payments page to be implemented

chore: add pay now button to unfulfilled payments

---

src/index.js
src/pages/paymentPage/paymentPage.js
src/pages/paymentPage/paymentStyles.js

This is the basic payment page will show more later

---

src/pages/login.js

Was a small change to the login (sorry for using this branch for that)
This is a small error message change so no

Payment page

---

src/pages/patientDashboard/patientDashboard.js

Adds routing to the payments page

chore: add transaction type to payments location state

---

src/index.js
src/pages/doctorDashboard/doctorDashboard.js
src/pages/login.js
src/pages/patientDashboard/patientDashboard.js
src/pages/registration.js

Just changed our logo text to the png for every page
NA
Nah it doesnt conflict with anything

Added logo to every single page

---

src/index.js

Just quickly fixed index.js naming issue
none
Nah

Fixed index.js error

---

src/pages/doctorDashboard/PostAppointment.css
src/pages/doctorDashboard/PostAppointment.js
src/pages/doctorDashboard/doctorDashboard.js

First feature of the `Post Appointment` Page - Charging the Patient money
Full e2e with frontend and backend

feat: add create payment to post appointment page

---

src/pages/doctorDashboard/PostAppointment.js

Doctors can only submit one payment for each appointment now lol

fix: return doctor to dashboard after data submission

---

src/pages/paymentPage/paymentPage.js

Finally finished the payment fulfill system

---

src/pages/paymentPage/paymentStyles.js
src/pages/registration.js
src/pages/registrationStyles.js

I just organized my css on the registration page
I'll let Michael know that I finished organizing things

Just small css orgnaization on the registration page

---

src/Components/DashboardTopBar/DashboardTopBar.css
src/Components/DashboardTopBar/DashboardTopBar.js
src/Components/Footer/Footer.css
src/Components/LandingPage/HeroSection.js
src/Components/LandingPage/Testimonials.css
src/index.css
src/pages/Registration/registration.js
src/pages/doctorDashboard/doctorDashboard.css
src/pages/doctorDashboard/doctorDashboard.js
src/pages/patientDashboard/patientDashboard.css
src/pages/patientDashboard/patientDashboard.js

The Top Dashboard bar is unified for Patient, Doctors, and Pharmacies. They have a profile section as well where you can view and edit your account details, change the dashboard to dark mode, and log out. Maybe I'll add a delete account option button?

Added Profile section for Dashboards and unfied the components

---

UIFrontendTests/landingpageTest.py
UIFrontendTests/loginTest.py
UIFrontendTests/registrationTest.py
UIFrontendTests/selenTesting.py

These are just me adding my UI testing scripts to the frontend 
The Landing page, part of the login page are done so far.
These are the tests for the UI
I'm just going to go down the line with people in the group members and try to show them the tests of the UI or talk to them to help make the tests go through more smoothly

The basic beginnings of ui testing scripts

---

src/pages/Login/login.js
src/pages/Registration/registration.js
src/pages/paymentPage/paymentPage.js

Added some stuff to my code section to make ui testing easier

---

src/Components/DashboardTopBar/DashboardTopBar.css
src/Components/DashboardTopBar/DashboardTopBar.js

Preferred Pharmacy is displayed for patient in top bar

feat: get endpoint for preferred status

---

src/pages/Registration/registration.js

Validation for zip code field. Will show the user the issue

fix: add zip code validation

---

package-lock.json
package.json
src/index.js
src/pages/discussionPosts/discussion.js

The basics of Discussion Board
Can send thing to the backend

Discussion Board section

---

src/pages/doctorDashboard/PostAppointment.css
src/pages/doctorDashboard/PostAppointment.js
src/pages/patientDashboard/patientDashboard.css
src/pages/patientDashboard/patientDashboard.js

- Allow doctors to submit prescriptions post appointment
- Allow patients to see prescriptions on new dashboard tab
E2E with frontend and both backends

feat: allow doctors to submit and patients to see prescriptions

---

package-lock.json
package.json
src/index.js
src/pages/Login/login.js
src/pages/patientDashboard/patientDashboard.js
src/pages/pharmacyDashboard/PharmacyDashboard.css
src/pages/pharmacyDashboard/PharmacyDashboard.js

Changes Made
Here I added the display functions for each of the endpoints in my backend on the pharmacy.
Testing Done
The manual step i took to test the prescription addition was run this insert from the mockdata file in the backend:
-- 17. Insert Prescriptions
INSERT INTO prescriptions (doctor_id, patient_id, pharmacy_id, medication_name, dosage, instructions, status) VALUES
(1, 1, 1, 'Medication A', '50mg', 'Take once daily', 'pending'),
Then click fulfill button if it clears inventory conflict.
the pharmacy_id is important to know and can be found using:
SELECT * from pharmacies; 
and typing in the one associated with your login. 
To test the add inventory you can just type it in the form displayed.
Testing both of these also allows us to test the completed transactions at the same …

Pharmacy page

---

src/pages/pharmacyDashboard/PharmacyDashboard.css
src/pages/pharmacyDashboard/PharmacyDashboard.js

- Prices tab on pharmacy dashboard. See current prices and update prices
- Error handling for out of stock on drug

feat: setup prices table

---

src/pages/pharmacyDashboard/PharmacyDashboard.js

- New Tab: `Dispense` tab where Pharmacists can mark a prescription as dispensed(A patient has picked up the prescription)
- When a prescription is marked as dispensed, a payment is generated for the patient based on the drug price

feat: setup pharmacy payments on prescription fill

---

src/pages/pharmacyDashboard/PharmacyDashboard.js

Missed one commit on that last PR

feat: add more stuff for prescriptions and payments

---

package-lock.json
package.json
src/pages/discussionPosts/discussion.js

You can add posts, comment on them and search them
I manually tested the UI myself

Meal plan discussion posts

---

src/pages/discussionPosts/discussion.js
src/pages/doctorDashboard/doctorDashboard.js
src/pages/patientDashboard/patientDashboard.js

Buttons for the Discussion Board along with a small sidebar change on the discussion board
I tested the UI manually along with accidentally with automated tests for the dashboard.

Dev branch made

---

src/pages/doctorDashboard/PostAppointment.js

Fix bug with assigning meal plans

fix: fix bug with assigning meal plans post appointment

---

src/pages/LandingPage/LandingPage.css
src/pages/LandingPage/landingPage.js
src/pages/patientDashboard/patientDashboard.js

Just made changes to metrics so it gets mealplan calories and additional

Implement meal selection and calculated calorie tracking

---

src/Components/LandingPage/Pharmacists.js

fix: change port on pharmacy list

---

UIFrontendTests/doctorTest.py
UIFrontendTests/landingpageTest.py
UIFrontendTests/patientTest.py
UIFrontendTests/pharmaTest.py
UIFrontendTests/registrationTest.py

UI tests are fully done for login and Registration
These are the UI tests

Login and Reg Fully done

---

UIFrontendTests/loginTest.py

fix: change placeholder password to actual value

---

.dockerignore
Dockerfile
good-eatz-react/.helmignore
good-eatz-react/Chart.yaml
good-eatz-react/templates/NOTES.txt
good-eatz-react/templates/_helpers.tpl
good-eatz-react/templates/deployment.yaml
good-eatz-react/templates/hpa.yaml
good-eatz-react/templates/ingress.yaml
good-eatz-react/templates/service.yaml
good-eatz-react/templates/serviceaccount.yaml
good-eatz-react/templates/tests/test-connection.yaml
good-eatz-react/values.yaml

Adding in Dockerfile and Helm charts. This is for CD pipeline

feat: setup react and helm

---

src/pages/discussionPosts/discussion.js

Made it more clear when selecting a meal plan to upload

Small UI and code change

---

good-eatz-react/templates/configmap.yaml
good-eatz-react/templates/deployment.yaml
good-eatz-react/values.yaml
public/config.json
src/Components/ChatHistory.jsx
src/Components/ChatWindow.jsx
src/Components/DashboardTopBar/DashboardTopBar.js
src/Components/LandingPage/Doctors.js
src/Components/LandingPage/Pharmacists.js
src/index.js
src/pages/Login/login.js
src/pages/Registration/registration.js
src/pages/discussionPosts/discussion.js
src/pages/doctorDashboard/PostAppointment.js
src/pages/doctorDashboard/doctorDashboard.js
src/pages/patientDashboard/PostAppointment.js
src/pages/patientDashboard/patientDashboard.js
src/pages/paymentPage/paymentPage.js

Now using a config file to get the ip address(either localhost:5000 or prod)

feat: switch to using config file for ip address

---

good-eatz-react/templates/configmap.yaml
good-eatz-react/values.yaml
public/config.json
src/index.js
src/pages/doctorDashboard/PostAppointment.js
src/pages/pharmacyDashboard/PharmacyDashboard.js

- Setting up frontend to work with pharma backend in prod

feat: configure frontend to connect to pharmacy backend in prod

---

.github/workflows/build-and-push.yml

Adding in build and push workflow
If anyone wants to know how our prod server works, just ask me

feat: add in docker workflow

---

src/Components/ChatHistory.jsx

- In chat history, user gets a drop down bar instead of searching by ID

fix: update history to show drop down for patients and doctors

---

src/pages/discussionPosts/discussion.js

Refined the Discussion Board. I added a refresh button, A button on the side to Minimize the sidebar. I cleaned up the visuals for the replies along with adding upvotes.
Manually but soon UI tested
I'm putting this in the channel

Discuss final

---

good-eatz-react/templates/deployment.yaml
good-eatz-react/values.yaml

- Should let me auto restart the pod on new commit

fix: add pod annotation

---

good-eatz-react/templates/deployment.yaml

fix: attempt fix for annotation

---

good-eatz-react/templates/restart-hook.yaml

fix: add post sync job to kick the pod

---

good-eatz-react/templates/service.yaml
good-eatz-react/values.yaml

feat: configure node port

---

UIFrontendTests/bookAppointmentTest.py

test: demo pipeline

---

src/pages/discussionPosts/discussion.js

Small tweak to the sidebar
Manually

Small ui change

---

UIFrontendTests/registrationTest.py
src/pages/Registration/registration.js
src/pages/discussionPosts/discussion.js

I forgot to add certain requirements to the registration so I added it
Manually, will try it out with Selenium shortly
This is going into the discord

Forgot to make Registration use a form

---

src/pages/Registration/registration.js

Covers edge cases in Registration along with error displays that were forgotten on the Registration Page
Manually tested with some discovered during UI tests
I'll let people know that this is my last change.

Smaller Registration changes
